### ISSUE TITLE
Rate limiting & sécurité API

### ISSUE THREAD

**Issue by Mysterken** [FichesFlow/ff-server#5]
## Objectif

Sécuriser l’API REST :

1. **Limiter le débit (rate limiting)** pour empêcher le brute-force sur `/api/login_check` et l’abus des routes publiques,
2. Renforcer les **en-têtes HTTP** et la politique **CORS**.

## Tâches

* [x] **Installer les dépendances**

  ```bash
  composer require symfony/rate-limiter
  composer require nelmio/cors-bundle

  composer require nelmio/security-bundle # si non présent
  ```

* [x] **Configurer les rate-limiters** dans `config/packages/rate_limiter.yaml`

  ```yaml
  rate_limiter:
    login:
      policy: 'fixed_window'
      limit: 5          # tentatives
      interval: '1 minute'
    anonymous_api:
      policy: 'token_bucket'
      limit: 100        # requêtes
      rate: { interval: '1 minute', amount: 100 }
    authenticated_api:
      policy: 'token_bucket'
      limit: 600
      rate: { interval: '1 minute', amount: 600 }
  ```

* [x] **Ajouter les attributs** `#[RateLimit('login')]`, `#[RateLimit('anonymous_api')]` ou un listener qui détecte `is_granted('IS_AUTHENTICATED_FULLY')` et applique la bonne limite.

* [x] **Configurer CORS** (`nelmio_cors.yaml`)

  * Origines autorisées : `http://localhost:5173`, futur domaine prod.
  * Méthodes : `GET, POST, PUT, PATCH, DELETE, OPTIONS`.
  * Headers exposés : `Authorization, Content-Type`.

* [x] **Activer les en-têtes de sécurité** (`nelmio_security.yaml`)

  * `content_security_policy` mode *report-only* (pour commencer)
  * `frame_options: DENY`, `xss_protection: 1; mode=block`
  * HSTS 1 an en prod.

## Critères d’acceptation

* Au-delà du quota défini, l’API renvoie **429** avec header `Retry-After`.
* Les requêtes CORS `OPTIONS` obtiennent `200` avec les bons headers, le front local fonctionne.
* Les headers `Strict-Transport-Security`, `X-Frame-Options`, `X-XSS-Protection` et un CSP sont présents en **prod**.
